import type { Metadata } from 'next'
import './globals.css'
import { ThemeProvider } from './theme-provider';
import ThemeSwitch from '@/components/ThemeSwitch';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`bg-slate-50 dark:bg-[#0d1117]`}>
        <main className='relative flex flex-col items-center justify-center'>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            {children}
          </ThemeProvider>
        </main>
      </body>
    </html>
  )
}
